//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint1Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Job
    {
        [Key]
        public string JobID { get; set; }
        public string jState { get; set; }
        public string SLoc { get; set; }
        public System.DateTime STime { get; set; }
        public string ELoc { get; set; }
        public System.DateTime ETA { get; set; }
        public string Dist { get; set; }
        public double BasicCost { get; set; }
        public Nullable<System.DateTime> ActArrive { get; set; }
        public double CHeight { get; set; }
        public double CLength { get; set; }
        public double CWidth { get; set; }
        public double CWeight { get; set; }
        public string AbLoad { get; set; }
        public double MBefore { get; set; }
        public Nullable<double> MAfter { get; set; }
        public double ExpctFuel { get; set; }
        public Nullable<double> ActFuel { get; set; }
        public string Flag { get; set; }
        public string TruckID { get; set; }
        public string CustomerID { get; set; }
        public string CargoID { get; set; }
        public string DriverNo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
