//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint1Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        [Key]
        public string TruckID { get; set; }
        public string Vin { get; set; }
        public string LP { get; set; }
        public string Tstat { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Chassis { get; set; }
        public string Cabin { get; set; }
        public string Engine { get; set; }
        public string Steering { get; set; }
        public string Powert { get; set; }
        public string Torque { get; set; }
        public string GearBox { get; set; }
        public int TankCap { get; set; }
        public int Milage { get; set; }
        public double Weight { get; set; }
        public double MaxLoad { get; set; }
        public System.DateTime PDate { get; set; }
        public System.DateTime LSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
